### ISSUE TITLE
Doesnt work at startup

### ISSUE THREAD

**Issue by Drako12** [Faceless3882/LG_Buddy#2]
I installed it today, and it works on shutdown, but it doesnt on startup, I do have a bootmanager and I understand it wont turn off before linux starts running, but even if I blindly hit enter to boot on my linux, it wont turn on the TV.

I know the library commands are working because I can use then to test like that

:~$ sleep 10;/usr/bin/LG_Buddy_PIP/bin/bscpylgtvcommand 192.168.0.116 button POWER;sleep 5;/usr/bin/LG_Buddy_PIP/bin/bscpylgtvcommand 192.168.0.116 set_input HDMI_1

but why doesnt work right after boot?

**Comment by Drako12** [comment]
not sure why, but it works after I tested. Maybe its because the TV asks for confirmation of the permission to both shutdown and start up and when I tested I gave the permission, now its working.

**Comment by Faceless3882** [comment]
Ah yes, that must have been it. Glad you got it working!

**Comment by 0ringleader** [comment]
Hey, had a similar issue with my TV. 
Starting it using your script didn't work, since the ip address isn't reachable, when it's off.
But by installing the wakeonlan package I can turn it on with the following script:

`#!/bin/bash

# Set variables
TV_IP="192.168.xxx.xxx"
TV_MAC="xx:xx:xx:xx:xx:xx"

startupdelay=10

#Initiate start delay.
sleep $startupdelay

# Function to send Wake-On-LAN packet
send_wol() {
    local ip=$1
    local mac=$2
    echo "Sending WOL packet to $ip..."
    #wakeonlan -i $ip $mac also doesn't work for me, since the ip is unavailable
    wakeonlan $mac
}



send_wol $TV_IP $TV_MAC

echo "Wake-On-LAN packet sent. The TV should wake up shortly."
`

Just wanted to leave the feedback, anyways thanks for your scripts!

**Comment by Faceless3882** [comment]
> Hey, had a similar issue with my TV. Starting it using your script didn't work, since the ip address isn't reachable, when it's off. But by installing the wakeonlan package I can turn it on with the following script:
> 
> `#!/bin/bash
> # Set variables
> 
> TV_IP="192.168.xxx.xxx" TV_MAC="xx:xx:xx:xx:xx:xx"
> 
> startupdelay=10
> 
> #Initiate start delay. sleep $startupdelay
> # Function to send Wake-On-LAN packet
> 
> send_wol() { local ip=$1 local mac=$2 echo "Sending WOL packet to $ip..." #wakeonlan -i $ip $mac also doesn't work for me, since the ip is unavailable wakeonlan $mac }
> 
> send_wol $TV_IP $TV_MAC
> 
> echo "Wake-On-LAN packet sent. The TV should wake up shortly." `
> 
> Just wanted to leave the feedback, anyways thanks for your scripts!

Nice one! Thanks for sharing
